# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.card import Card
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class InlineResponse200(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, middle_card: Card=None, players_cards: List[Card]=None):
        """
        InlineResponse200 - a model defined in Swagger

        :param middle_card: The middle_card of this InlineResponse200.
        :type middle_card: Card
        :param players_cards: The players_cards of this InlineResponse200.
        :type players_cards: List[Card]
        """
        self.swagger_types = {
            'middle_card': Card,
            'players_cards': List[Card]
        }

        self.attribute_map = {
            'middle_card': 'middleCard',
            'players_cards': 'playersCards'
        }

        self._middle_card = middle_card
        self._players_cards = players_cards

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.
        :rtype: InlineResponse200
        """
        return deserialize_model(dikt, cls)

    @property
    def middle_card(self) -> Card:
        """
        Gets the middle_card of this InlineResponse200.

        :return: The middle_card of this InlineResponse200.
        :rtype: Card
        """
        return self._middle_card

    @middle_card.setter
    def middle_card(self, middle_card: Card):
        """
        Sets the middle_card of this InlineResponse200.

        :param middle_card: The middle_card of this InlineResponse200.
        :type middle_card: Card
        """

        self._middle_card = middle_card

    @property
    def players_cards(self) -> List[Card]:
        """
        Gets the players_cards of this InlineResponse200.

        :return: The players_cards of this InlineResponse200.
        :rtype: List[Card]
        """
        return self._players_cards

    @players_cards.setter
    def players_cards(self, players_cards: List[Card]):
        """
        Sets the players_cards of this InlineResponse200.

        :param players_cards: The players_cards of this InlineResponse200.
        :type players_cards: List[Card]
        """

        self._players_cards = players_cards

